### ISSUE TITLE
The image becomes darker after using this shader

### ISSUE THREAD

**Issue by Gao-JF** [quic/snapdragon-gsr#1]
Hi, I used sgsr_shader_mobile.frag on Pico4 based on OpenGL ES 3.0. First, I loaded a 1080P texture into an FBO and then drew it onto a 4K texture bound to another FBO. While drawing, I used sgsr_shader_mobile.frag with the following parameters: 
OperationMode 1 (RGBA)
EdgeThreshold 4.0/255.0, 
EdgeSharpness 2.0 

I found that the resulting image became darker compared to the original image. Did I do something wrong? How should I correctly use this shader?

**source (1080P):**
![maya](https://github.com/quic/snapdragon-gsr/assets/63134892/d8336fde-2a67-4ce5-990d-a2be7632b79e)
**lerp (4K):**
![maya_lerp](https://github.com/quic/snapdragon-gsr/assets/63134892/3b509a9e-0f06-4cbc-a7b0-6fe7d682b658)
**SGSR (4K, Params: OperationMode 1, EdgeThreshold 4.0/255.0, EdgeSharpness 2.0):** 
![maya_rgba_4|255_2](https://github.com/quic/snapdragon-gsr/assets/63134892/76799292-ce9a-426f-9f89-0fe9cbca9d38)

**Comment by Gao-JF** [comment]
I used another image and found that the visual effect of the resulting drawing did not improve either.

**Source (512 * 512):**
![lena_source](https://github.com/quic/snapdragon-gsr/assets/63134892/e91cfddf-5c6a-4069-bb28-bfc7f45d348b)
**Lerp (1024 * 1024):**
![lena_lerp](https://github.com/quic/snapdragon-gsr/assets/63134892/d7b7d9ea-2047-4a31-9b17-eec7a41163ea)
**SGSR (1024 * 1024, Params: OperationMode 1, EdgeThreshold 4.0/255.0, EdgeSharpness 2.0):**
![lena_rgba_4|255_2 0](https://github.com/quic/snapdragon-gsr/assets/63134892/68ead269-1fce-4eb3-a63d-3f5e4ea4a7d8)

Appreciate if someone can help.

**Comment by s1ddok** [comment]
@Gao-JF have you find a solution to this? results aren't great for me either :(

**Comment by Gao-JF** [comment]
> @Gao-JF have you find a solution to this? results aren't great for me either :(

Hi, I pass parameters to the shader's `uniform ViewportInfo[1]`, and it seems to work!

**Comment by s1ddok** [comment]
@Gao-JF and what do you pass? I'm trying to pass (0, 0, width, height) but I still get bad results like yours

**Comment by Gao-JF** [comment]
> @Gao-JF and what do you pass? I'm trying to pass (0, 0, width, height) but I still get bad results like yours

I read the code of shader and I guess is (1.0 / width, 1.0 / height, width, height)
